### ISSUE TITLE
Afficher la date de fin de la constitution courante

### ISSUE THREAD

**Issue by rakruk** [TableauBits/Yatga#104]
Genre en gros (`font-size: large`) et en blanc sur fond rouge en date relative.

**Comment by hvdbm** [comment]
Pour faire ça, il faudrait qu'on ajoute deux champs à un objet `constitution` : `startDate` et `endDate`. Aussi je pense que ça serait mieux d'avoir un décompte du style "il reste X jours et Y heures avant la fin".

**Comment by rakruk** [comment]
![image](https://user-images.githubusercontent.com/43119833/205414863-32e7357c-a81e-4220-bf8c-1913714b719e.png)

> "il reste X jours et Y heures avant la fin".
c'est ce que je voulais dire par "date relative"
