### ISSUE TITLE
Erreur logique de `||` dans switch case

### ISSUE THREAD

**Issue by rakruk** [TableauBits/Yatga#84]
![image](https://user-images.githubusercontent.com/43119833/193300487-95c59ec7-f78b-4833-be8e-26306881d4cb.png)
![image](https://user-images.githubusercontent.com/43119833/193300638-7ebf09d6-9775-4261-9a38-d0f778e65c46.png)

Dans src/app/components/constitution-page/constitution.component.ts
et src/app/components/constitution-page/manage-songs/manage-songs.component.ts

**Comment by hvdbm** [comment]
@Ithyx Ça veut dire qu'on a la même erreur sur Kalimba

**Comment by Ithyx** [comment]
Exact, je viens de vérifier, il est uniquement présent dans le module d'invitation
