### ISSUE TITLE
Configuration de github actions et règles de merge

### ISSUE THREAD

**Issue by rakruk** [TableauBits/Yatga#95]
Je n'ai pas accès au settings de Github, est-ce-que quelqu'un peut confirmer que ces settings sont enable pour la branche main et release? 

![image](https://user-images.githubusercontent.com/43119833/204334735-7665fea7-c5f6-4a56-a987-4469f6331eac.png)
![image](https://user-images.githubusercontent.com/43119833/204334924-e82561e7-5c9b-43fe-8b96-07aa9f2e5d5f.png)

**Comment by rakruk** [comment]
Linked with #94

**Comment by Ithyx** [comment]
oui tout est bien configuré
