### ISSUE TITLE
Retirer le bouton retirer de "Gérer mes chansons"

### ISSUE THREAD

**Issue by rakruk** [TableauBits/Yatga#96]
![image](https://user-images.githubusercontent.com/43119833/204579886-62ae4249-eb84-4ed6-bde5-abea6a773df8.png)

Je ne pense pas que l'utilisation soit très élevée sachant qu'on a ça sur l'interface des cartes

**Comment by hvdbm** [comment]
À y réfléchir après fait.
* #97
