### ISSUE TITLE
Ajouter le bouton "Retirer la chanson" sur l'interface table

### ISSUE THREAD

**Issue by rakruk** [TableauBits/Yatga#97]
Ce bouton: 
![image](https://user-images.githubusercontent.com/43119833/204580165-ac7230c2-4de8-4832-8326-5f8928652c7b.png) est manquante de l'interface tableau. Serrai-ce possible de créer ca sur l'interface tableau?

**Comment by hvdbm** [comment]
Oui. Je pourrais m'en charger.
